version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./recipe:/app
    command: >
      sh -c "python manage.py wait_for_db &&
       python manage.py migrate &&
       python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipedb
      - DB_USER=recipedb
      - DB_PASSWORD=recipepass
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - recipe-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipedb
      - POSTGRES_USER=recipeuser
      - POSTGRES_PASSWORD=recipepass

volumes:
  recipe-postgres-data:
